### ISSUE TITLE
outdated module

### ISSUE THREAD

**Issue by Phidel69** [TheanYeeSin/Python-Mental-Health-Chatbot#1]
the latest version of python doesn't support TensorFlow
so i haven't even been able to run the main python file

**Comment by TheanYeeSin** [comment]
TensorFlow is supported up till python 3.12 currently, you can downgrade it, but it shouldn't affect anything, because the version required for this project are all written in `requirements.txt`, and if you want to use this with latest version, please fork it and update yourself, this is no longer in development
